// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crawler.proto

package crawler

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ZhiHuReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZhiHuReq) Reset()         { *m = ZhiHuReq{} }
func (m *ZhiHuReq) String() string { return proto.CompactTextString(m) }
func (*ZhiHuReq) ProtoMessage()    {}
func (*ZhiHuReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{0}
}

func (m *ZhiHuReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZhiHuReq.Unmarshal(m, b)
}
func (m *ZhiHuReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZhiHuReq.Marshal(b, m, deterministic)
}
func (m *ZhiHuReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZhiHuReq.Merge(m, src)
}
func (m *ZhiHuReq) XXX_Size() int {
	return xxx_messageInfo_ZhiHuReq.Size(m)
}
func (m *ZhiHuReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ZhiHuReq.DiscardUnknown(m)
}

var xxx_messageInfo_ZhiHuReq proto.InternalMessageInfo

type ZhiHuResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZhiHuResp) Reset()         { *m = ZhiHuResp{} }
func (m *ZhiHuResp) String() string { return proto.CompactTextString(m) }
func (*ZhiHuResp) ProtoMessage()    {}
func (*ZhiHuResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{1}
}

func (m *ZhiHuResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZhiHuResp.Unmarshal(m, b)
}
func (m *ZhiHuResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZhiHuResp.Marshal(b, m, deterministic)
}
func (m *ZhiHuResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZhiHuResp.Merge(m, src)
}
func (m *ZhiHuResp) XXX_Size() int {
	return xxx_messageInfo_ZhiHuResp.Size(m)
}
func (m *ZhiHuResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ZhiHuResp.DiscardUnknown(m)
}

var xxx_messageInfo_ZhiHuResp proto.InternalMessageInfo

type ZhiHuNoResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZhiHuNoResp) Reset()         { *m = ZhiHuNoResp{} }
func (m *ZhiHuNoResp) String() string { return proto.CompactTextString(m) }
func (*ZhiHuNoResp) ProtoMessage()    {}
func (*ZhiHuNoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{2}
}

func (m *ZhiHuNoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZhiHuNoResp.Unmarshal(m, b)
}
func (m *ZhiHuNoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZhiHuNoResp.Marshal(b, m, deterministic)
}
func (m *ZhiHuNoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZhiHuNoResp.Merge(m, src)
}
func (m *ZhiHuNoResp) XXX_Size() int {
	return xxx_messageInfo_ZhiHuNoResp.Size(m)
}
func (m *ZhiHuNoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ZhiHuNoResp.DiscardUnknown(m)
}

var xxx_messageInfo_ZhiHuNoResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ZhiHuReq)(nil), "crawler.ZhiHuReq")
	proto.RegisterType((*ZhiHuResp)(nil), "crawler.ZhiHuResp")
	proto.RegisterType((*ZhiHuNoResp)(nil), "crawler.ZhiHuNoResp")
}

func init() { proto.RegisterFile("crawler.proto", fileDescriptor_84c7eabcfe7807d1) }

var fileDescriptor_84c7eabcfe7807d1 = []byte{
	// 104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x2e, 0x4a, 0x2c,
	0xcf, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xb8, 0xb8,
	0x38, 0xa2, 0x32, 0x32, 0x3d, 0x4a, 0x83, 0x52, 0x0b, 0x95, 0xb8, 0xb9, 0x38, 0xa1, 0xec, 0xe2,
	0x02, 0x25, 0x5e, 0x2e, 0x6e, 0x30, 0xc7, 0x2f, 0x1f, 0xc4, 0x35, 0xb2, 0xe1, 0x82, 0x69, 0x11,
	0x32, 0xe4, 0xe2, 0x28, 0x2a, 0xcd, 0x03, 0x4b, 0x0a, 0x09, 0xea, 0xc1, 0xcc, 0x85, 0x99, 0x22,
	0x25, 0x84, 0x2e, 0x54, 0x5c, 0x90, 0xc4, 0x06, 0xb6, 0xd5, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0x0c, 0xa0, 0xc8, 0x9f, 0x86, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CrawlerClient is the client API for Crawler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CrawlerClient interface {
	RunZhiHu(ctx context.Context, in *ZhiHuReq, opts ...grpc.CallOption) (*ZhiHuResp, error)
}

type crawlerClient struct {
	cc *grpc.ClientConn
}

func NewCrawlerClient(cc *grpc.ClientConn) CrawlerClient {
	return &crawlerClient{cc}
}

func (c *crawlerClient) RunZhiHu(ctx context.Context, in *ZhiHuReq, opts ...grpc.CallOption) (*ZhiHuResp, error) {
	out := new(ZhiHuResp)
	err := c.cc.Invoke(ctx, "/crawler.crawler/runZhiHu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrawlerServer is the server API for Crawler service.
type CrawlerServer interface {
	RunZhiHu(context.Context, *ZhiHuReq) (*ZhiHuResp, error)
}

// UnimplementedCrawlerServer can be embedded to have forward compatible implementations.
type UnimplementedCrawlerServer struct {
}

func (*UnimplementedCrawlerServer) RunZhiHu(ctx context.Context, req *ZhiHuReq) (*ZhiHuResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunZhiHu not implemented")
}

func RegisterCrawlerServer(s *grpc.Server, srv CrawlerServer) {
	s.RegisterService(&_Crawler_serviceDesc, srv)
}

func _Crawler_RunZhiHu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZhiHuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlerServer).RunZhiHu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crawler.crawler/RunZhiHu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlerServer).RunZhiHu(ctx, req.(*ZhiHuReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Crawler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "crawler.crawler",
	HandlerType: (*CrawlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "runZhiHu",
			Handler:    _Crawler_RunZhiHu_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crawler.proto",
}
