// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	captcha "hothothot/service/gateway/internal/handler/captcha"
	password "hothothot/service/gateway/internal/handler/password"
	user "hothothot/service/gateway/internal/handler/user"
	"hothothot/service/gateway/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
		},
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/password/resetcode",
				Handler: password.ResetCodeHandler(serverCtx),
			},
		},
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/password/reset",
				Handler: password.ResetHandler(serverCtx),
			},
		},
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/password/change",
				Handler: password.ChangeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/captcha",
				Handler: captcha.CaptchaHandler(serverCtx),
			},
		},
	)
}
