// Code generated by goctl. DO NOT EDIT!
// Source: system.proto

//go:generate mockgen -destination ./system_mock.go -package systemclient -source $GOFILE

package systemclient

import (
	"context"

	"hothothot/service/system/rpc/system"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	NameReq  = system.NameReq
	NameResp = system.NameResp

	System interface {
		GetByName(ctx context.Context, in *NameReq) (*NameResp, error)
	}

	defaultSystem struct {
		cli zrpc.Client
	}
)

func NewSystem(cli zrpc.Client) System {
	return &defaultSystem{
		cli: cli,
	}
}

func (m *defaultSystem) GetByName(ctx context.Context, in *NameReq) (*NameResp, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.GetByName(ctx, in)
}
