// Code generated by goctl. DO NOT EDIT!
// Source: system.proto

package server

import (
	"context"

	"hothothot/service/system/rpc/internal/logic"
	"hothothot/service/system/rpc/internal/svc"
	"hothothot/service/system/rpc/system"
)

type SystemServer struct {
	svcCtx *svc.ServiceContext
}

func NewSystemServer(svcCtx *svc.ServiceContext) *SystemServer {
	return &SystemServer{
		svcCtx: svcCtx,
	}
}

func (s *SystemServer) GetByName(ctx context.Context, in *system.NameReq) (*system.NameResp, error) {
	l := logic.NewGetByNameLogic(ctx, s.svcCtx)
	return l.GetByName(in)
}
