// Code generated by goctl. DO NOT EDIT!
// Source: crawler.proto

package server

import (
	"context"

	"hothothot/service/crawler/rpc/crawler"
	"hothothot/service/crawler/rpc/internal/logic"
	"hothothot/service/crawler/rpc/internal/svc"
)

type CrawlerServer struct {
	svcCtx *svc.ServiceContext
}

func NewCrawlerServer(svcCtx *svc.ServiceContext) *CrawlerServer {
	return &CrawlerServer{
		svcCtx: svcCtx,
	}
}

func (s *CrawlerServer) RunZhiHu(ctx context.Context, in *crawler.ZhiHuReq) (*crawler.ZhiHuNoResp, error) {
	l := logic.NewRunZhiHuLogic(ctx, s.svcCtx)
	return l.RunZhiHu(in)
}

func (s *CrawlerServer) RunWeather(ctx context.Context, in *crawler.WeatherReq) (*crawler.WeatherNoResp, error) {
	l := logic.NewRunWeatherLogic(ctx, s.svcCtx)
	return l.RunWeather(in)
}
