// Code generated by goctl. DO NOT EDIT!
// Source: crawler.proto

//go:generate mockgen -destination ./crawler_mock.go -package crawlerclient -source $GOFILE

package crawlerclient

import (
	"context"

	"hothothot/service/crawler/rpc/crawler"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	ZhiHuReq    = crawler.ZhiHuReq
	ZhiHuResp   = crawler.ZhiHuResp
	ZhiHuNoResp = crawler.ZhiHuNoResp

	Crawler interface {
		RunZhiHu(ctx context.Context, in *ZhiHuReq) (*ZhiHuResp, error)
	}

	defaultCrawler struct {
		cli zrpc.Client
	}
)

func NewCrawler(cli zrpc.Client) Crawler {
	return &defaultCrawler{
		cli: cli,
	}
}

func (m *defaultCrawler) RunZhiHu(ctx context.Context, in *ZhiHuReq) (*ZhiHuResp, error) {
	client := crawler.NewCrawlerClient(m.cli.Conn())
	return client.RunZhiHu(ctx, in)
}
