// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username  string `json:"username"`
	Password  string `json:"password"`
	Captcha   string `json:"captcha"`
	CaptchaId string `json:"captchaId"`
}

type LoginResp struct {
	Id           int64  `json:"id"`
	Username     string `json:"username"`
	Nickname     string `json:"nickname"`
	Mail         string `json:"mail"`
	Gender       string `json:"gender"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type PwdResetCodeReq struct {
	Username string `json:"username"`
}

type PwdResetCodeResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type PwdResetReq struct {
	Username        string `json:"username"`
	NewPassword     string `json:"newPassword"`
	ComparePassword string `json:"comparePassword"`
	ResetCode       string `json:"resetCode"`
}

type PwdResetResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type PwdChangeReq struct {
	Password        string `json:"password"`
	NewPassword     string `json:"newPassword"`
	ComparePassword string `json:"comparePassword"`
}

type PwdChangeResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}
